spring:
  application:
      name: activityservice
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/aiactivityfitness

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

server:
  port: 8082
  servlet:
    context-path: /api/v1

