spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: activity-processor-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 1

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.use.type.headers: false
        spring.json.value.default.type: com.saif.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

        session.timeout.ms: 120000       # 2 minutes
        max.poll.interval.ms: 300000     # 5 minutes
        request.timeout.ms: 120000       # 2 minutes

kafka:
  topic:
    name: activity-events

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

server:
  port: 8083

openrouter:
  api:
    key: ${OPENROUTER_API_KEY}
    url: ${OPENROUTER_API_URL}