spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness-micro-user
    username: postgres
    password: saif12

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api/v1
  port: 8081